version = "Two"
max_width = 90
use_small_heuristics = "Max" # Replace with the one below when rustfmt hits 2.0
#width_heuristics = "Max"
tab_spaces = 2
hard_tabs = false
newline_style = "Unix"
imports_layout = "HorizontalVertical"
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
